-- AlterTable
ALTER TABLE `center` MODIFY `zone` ENUM('ABU_DHABI', 'AJMAN', 'DUBAI', 'FUJAIRAH', 'RAS_AL_KHAIMAH', 'SHARJAH', 'UMM_AL_QUWAIN', 'AIN') NULL;

-- AlterTable
ALTER TABLE `user` ADD COLUMN `cvImage` VARCHAR(191) NULL,
    MODIFY `zone` ENUM('ABU_DHABI', 'AJMAN', 'DUBAI', 'FUJAIRAH', 'RAS_AL_KHAIMAH', 'SHARJAH', 'UMM_AL_QUWAIN', 'AIN') NULL;
